# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\"e\n\x12MsgDeliveryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x11\n\tinterface\x18\x03 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x05\"T\n\x13MsgDeliveryResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x05\x12\x0e\n\x06result\x18\x04 \x01(\t\",\n\x0cQueryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\">\n\rQueryResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x05\"=\n\x0e\x44\x65positRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\r\n\x05money\x18\x03 \x01(\x05\"?\n\x0f\x44\x65positResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\t\">\n\x0fWithdrawRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\r\n\x05money\x18\x03 \x01(\x05\"@\n\x10WithdrawResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\t\"*\n\x17PropagateDepositRequest\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x05\"*\n\x18PropagateDepositResponse\x12\x0e\n\x06result\x18\x03 \x01(\t\"+\n\x18PropagateWithdrawRequest\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x05\"+\n\x19PropagateWithdrawResponse\x12\x0e\n\x06result\x18\x03 \x01(\t2B\n\x04\x42\x61nk\x12:\n\x0bMsgDelivery\x12\x13.MsgDeliveryRequest\x1a\x14.MsgDeliveryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MSGDELIVERYREQUEST']._serialized_start=14
  _globals['_MSGDELIVERYREQUEST']._serialized_end=115
  _globals['_MSGDELIVERYRESPONSE']._serialized_start=117
  _globals['_MSGDELIVERYRESPONSE']._serialized_end=201
  _globals['_QUERYREQUEST']._serialized_start=203
  _globals['_QUERYREQUEST']._serialized_end=247
  _globals['_QUERYRESPONSE']._serialized_start=249
  _globals['_QUERYRESPONSE']._serialized_end=311
  _globals['_DEPOSITREQUEST']._serialized_start=313
  _globals['_DEPOSITREQUEST']._serialized_end=374
  _globals['_DEPOSITRESPONSE']._serialized_start=376
  _globals['_DEPOSITRESPONSE']._serialized_end=439
  _globals['_WITHDRAWREQUEST']._serialized_start=441
  _globals['_WITHDRAWREQUEST']._serialized_end=503
  _globals['_WITHDRAWRESPONSE']._serialized_start=505
  _globals['_WITHDRAWRESPONSE']._serialized_end=569
  _globals['_PROPAGATEDEPOSITREQUEST']._serialized_start=571
  _globals['_PROPAGATEDEPOSITREQUEST']._serialized_end=613
  _globals['_PROPAGATEDEPOSITRESPONSE']._serialized_start=615
  _globals['_PROPAGATEDEPOSITRESPONSE']._serialized_end=657
  _globals['_PROPAGATEWITHDRAWREQUEST']._serialized_start=659
  _globals['_PROPAGATEWITHDRAWREQUEST']._serialized_end=702
  _globals['_PROPAGATEWITHDRAWRESPONSE']._serialized_start=704
  _globals['_PROPAGATEWITHDRAWRESPONSE']._serialized_end=747
  _globals['_BANK']._serialized_start=749
  _globals['_BANK']._serialized_end=815
# @@protoc_insertion_point(module_scope)
